project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

